#!/bin/sh /etc/rc.common
# Copyright (C) 2015 brglng@github.com

START=99
STOP=99

start() {
        service_start /usr/bin/syncthing 2>&1 | logger &
}

stop() {
        service_stop /usr/bin/syncthing
}
